### ISSUE TITLE
Crashed computer when running on WSL

### ISSUE THREAD

**Issue by ryandikdan** [k-soliman/DeepFl-LogP#1]
Hello, I was looking to try out your program, but when I followed the installation instructions, upon running the python script it chased my computer. I am working on WSL in Windows 11. I noted the error had to do with protobuf being too update, so I downgraded it to 3.20.1 using pip and reran your python script, but then got the following error which seems like a compatibility issue with the packages. 
`Traceback (most recent call last):
  File "DeepFl-LogP.py", line 16, in <module>
    model = tf.keras.models.load_model(r"2020_DNN_v44_epoch_78_r0.892_rms0.359.h5")
  File "/home/ryan/anaconda3/envs/KarLogP/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 143, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/ryan/anaconda3/envs/KarLogP/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 160, in load_model_from_hdf5
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'`
Are there other specific package downgrades I can do that would help the script to run? What version were all of your packages when you ran it? Thanks!

In this environment pip says my packages are as such:
`Package              Version
-------------------- ---------
absl-py              1.2.0
astor                0.8.1
Bottleneck           1.3.5
certifi              2022.6.15
cycler               0.11.0
fonttools            4.36.0
gast                 0.2.2
google-pasta         0.2.0
greenlet             1.1.2
grpcio               1.47.0
h5py                 3.7.0
importlib-metadata   4.12.0
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2
kiwisolver           1.4.4
Markdown             3.4.1
MarkupSafe           2.1.1
matplotlib           3.5.3
mordred              1.2.0
munkres              1.1.4
networkx             2.6.3
numexpr              2.8.3
numpy                1.21.6
olefile              0.46
opt-einsum           3.3.0
packaging            21.3
pandas               1.3.5
Pillow               6.2.1
pip                  22.2.2
protobuf             3.20.1
pycairo              1.21.0
pyparsing            3.0.9
python-dateutil      2.8.2
pytz                 2022.2.1
reportlab            3.5.68
setuptools           65.1.0
six                  1.16.0
SQLAlchemy           1.4.40
tensorboard          1.15.0
tensorflow           1.15.0
tensorflow-estimator 1.15.1
termcolor            1.1.0
typing_extensions    4.3.0
unicodedata2         14.0.0
Werkzeug             2.2.2
wheel                0.37.1
wrapt                1.14.1
zipp                 3.8.1`

**Comment by k-soliman** [comment]
What is the python version you run?
